<p><b>[INFO]</b>&nbsp;POST Request : url=https://qa.api.zinnia.io/case/v1/tasks/message <br> path_url=/case/v1/tasks/message <br> headers={'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'application/json', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlU1SWNUOEQ4LTNWdl80NDFIdnlzbyJ9.eyJodHRwczovL3FhLmFwaS56aW5uaWEuaW8vY2xpZW50SWRzIjpbImV2ZXJseSIsImVsaWMiLCJzYnVsIl0sImh0dHBzOi8vcWEuYXBpLnppbm5pYS5pby9wZXJtaXNzaW9ucyI6WyJyZWFkOnBvbGljeSIsIndyaXRlOnBvbGljeSIsIndyaXRlOmNhc2UiLCJyZWFkOmNhc2UiLCJyZWFkOmRvY3VtZW50Iiwid3JpdGU6ZG9jdW1lbnQiLCJ3cml0ZTp0YXNrIiwicmVhZDp0YXNrIl0sInBhcnR5SWQiOiJjNmE3YWI5ZjdkZDg0MDE1YTY1NTJiZmM1YjM2NmI3NyIsInNvdXJjZSI6IkJ1c2luZXNzIFByb2Nlc3MgTWFuYWdlbWVudCIsImlzcyI6Imh0dHBzOi8vbG9naW4ucWEuemlubmlhLmNvbS8iLCJzdWIiOiJVdU1yaWJyUDNlOHpWaGZIeTZ3UEoyNWxWWWgxQ1dOM0BjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9xYS5hcGkuemlubmlhLmlvIiwiaWF0IjoxNzU4NjI3MTkzLCJleHAiOjE3NTg3MTM1OTMsInNjb3BlIjoib3BlbmlkIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIiwiYXpwIjoiVXVNcmliclAzZTh6VmhmSHk2d1BKMjVsVlloMUNXTjMifQ.JnVbRifLO_DxfJieg0yOHsvbGguCnp4y-TvSUuexiywb6KemJsmV-5_lp29Tku3puXejsJ5JiI9PWu4nyYsVafreeD4C_t5kfSnKm9cWOlDd7LqYVNA0txaRuCn7EeOrDDFmw2BjTHsEMkXc3f0DLPT6jS2aS5NoTNxoQU8QJuapwtRrgZTDgBNj-irDFUQORHVhclBkjavfbVUmR10EW7zSEn0XhL4bVOZHhChrJtsdnErJ1rbF6qzlMd0BwTr0CR8uwL145gOz3meOW44TLmaNtZFrC_a_lh1Nz-ZHK86P7mWliQQcs3fbj0KdSnp0h5Pmxu_oXC8B4nOYJKW05Q', 'Content-Length': '182'} <br> body=b'{"taskType": "SUITABILITY_REVI", "carrier": "MASS", "category": "SCHEDULED_REASON", "messageId": "DOCUMENT_MISSING", "message": "Document is missing for SUITABILITY_REVIEW for MASS"}' <br> </p><p><b>[INFO]</b>&nbsp;POST Response : url=https://qa.api.zinnia.io/case/v1/tasks/message <br> status=400, reason=Bad Request <br> headers={'Content-Type': 'application/json', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Expires': '0', 'X-Frame-Options': 'DENY', 'x-correlation-id': '317881f0-8af4-4e5e-83ab-6d62fd008f36', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Date': 'Tue, 23 Sep 2025 11:33:19 GMT', 'Content-Length': '206', 'Set-Cookie': 'AWSALBTG=KlcS3Eza1t4Og9ywcIw86WWuNIQmwOOxX0huO+A/ovb4d/dbz6LtrWWUT1x5s6OjRpCV0XHcvOMY4GgaTQeydu3jwwogE6x9JytRkq+2DnWQcYMVCwcfYgiIVL2ypjKXk5HsEKyNqVME7ZLUYE83BbJTZr5ylqY/AIFbuvVEpB/z; Expires=Tue, 30 Sep 2025 11:33:19 GMT; Path=/, AWSALBTGCORS=KlcS3Eza1t4Og9ywcIw86WWuNIQmwOOxX0huO+A/ovb4d/dbz6LtrWWUT1x5s6OjRpCV0XHcvOMY4GgaTQeydu3jwwogE6x9JytRkq+2DnWQcYMVCwcfYgiIVL2ypjKXk5HsEKyNqVME7ZLUYE83BbJTZr5ylqY/AIFbuvVEpB/z; Expires=Tue, 30 Sep 2025 11:33:19 GMT; Path=/; SameSite=None; Secure, AWSALB=mUdhrHp05w5Jz8P8ELKHMx6j+9sVnhWMntwq+VX8Nj5oOK6/jbH/YH7hQBjTxV81J8fF/lJXRff7x8Avm8FiDPgknhaUVnKAcqizV+qlwRRkM//fLBNiX8pcH558; Expires=Tue, 30 Sep 2025 11:33:19 GMT; Path=/, AWSALBCORS=mUdhrHp05w5Jz8P8ELKHMx6j+9sVnhWMntwq+VX8Nj5oOK6/jbH/YH7hQBjTxV81J8fF/lJXRff7x8Avm8FiDPgknhaUVnKAcqizV+qlwRRkM//fLBNiX8pcH558; Expires=Tue, 30 Sep 2025 11:33:19 GMT; Path=/; SameSite=None; Secure', 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'Host', 'X-Kong-Upstream-Latency': '44', 'X-Kong-Proxy-Latency': '21', 'Via': 'kong/3.6.1.6-enterprise-edition', 'X-Kong-Request-Id': '308e297f9ba63a2c42bf652d6c60e739'} <br> body={"statusCode":400,"timestamp":"2025-09-23T11:33:19.366Z","errorId":"de43fda6-0f55-4c51-8eaf-7ff74e50b770","message":"A task message with the same taskType, carrier, category, and messageId already exists."} <br> </p><p><b>[INFO]</b>&nbsp;C:\Users\sharmash\AppData\Roaming\Python\Python312\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'qa.api.zinnia.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings<br>  warnings.warn(</p><p style="color: red"><b>[FAIL]</b>&nbsp;HTTPError: 400 Client Error: Bad Request for url: https://qa.api.zinnia.io/case/v1/tasks/message</p>